apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-efs-pvc
spec:
  storageClassName: aws-efs
spec:
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 10Gi