apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-nfs-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: thick-disk
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 5Gi