es_host: elasticsearch.default
es_port: 9200
name: Demo-service
type: any
index: dw-demo-*
num_events: 1
filter:
- query:
    query_string:
      query: "Severity: \"SEVERITY-1\" AND PipelineName: \"Demo\"AND namespace:(-stg)"
alert:
- "pagerduty"
alert_subject:  "Env: prod - Demo - Type: Application(service)"
pagerduty_service_key: 12345
pagerduty_client_name: elastalert
