apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-efs-pvc
  namespace: devops
spec:
  storageClassName: aws-efs
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 10Gi
