modules:
  http_check:
    prober: http
    timeout: 30s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: [200, 0]  # Defaults to 2xx
#      fail_if_not_matches_regexp:
#      - "/nifi"
#################################################
